### ISSUE TITLE
Configure CORS

### ISSUE THREAD

**Issue by rngadam** [Aesirry/CoderBunker-Faces#5]
I don't see any Access-Control-Allow-Origin being returned by QingStor... How did you test this locally? You should add localhost:3000 or localhost:8080 or something to allow cross-site requests:

![screen shot 2017-04-26 at 8 11 44 pm](https://cloud.githubusercontent.com/assets/538542/25433910/c31ae9ae-2abc-11e7-846c-f46827813443.png)

This is to solve this browser error:

```
XMLHttpRequest cannot load https://sh1a.qingstor.com/cbfaces/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```

**Comment by jpbeltrami** [comment]
![image](https://cloud.githubusercontent.com/assets/14979915/25897757/0c872fea-353e-11e7-9984-32bdbc00dfd4.png)

I added these origins, seems like this works
